In [ ]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None #學生的分數
#scores_df:DataFrame | None = None #學生分數的DataFram

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,
                         columns=['國文', '英文', '數學', '地理', '歷史'],
                         index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名' , '性別']] = names_df [['姓名' , '性別']].head(n=50).values
scores_df = scores_df[['姓名' , '性別' ,'國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   楊志明  男  55  70  94  50  57
7    蕭博  男  80  47  77  69  73
8    馬芳  女  67  89  91  72  61
9   鄧雅婷  女  57  93  68  77  72
10   任廷  男  64  54  84  74  82

In [10]:
scores_df[scores_df['姓名'] =='鄧雅婷']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60")

     姓名 性別  國文  英文  數學  地理  歷史
9   鄧雅婷  女  57  93  68  77  72
11   馮敏  女  55  44  87  54  83
15  蔣嘉玲  女  55  56  78  96  47
24  余怡慈  女  56  63  96  80  73
38   丁穎  女  48  99  45  94  64
48   邱琳  女  59  95  84  85  47